/*
 * Created on 2022-01-04 ( 14:24:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Datalog;

public class DatalogData {

	private static Datalog entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Datalog newEntity = new Datalog();
		newEntity.setDatalogid( Integer.valueOf(100) ) ;
		newEntity.setMainnumber( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setMaintype( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setSubnumber( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setSubtype( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setStatus( Integer.valueOf(100) ) ;
		newEntity.setRemarks( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setDatatags( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setCreated( java.sql.Timestamp.valueOf("2001-05-21 01:46:52") ) ;
		newEntity.setUpdated( java.sql.Timestamp.valueOf("2001-05-21 01:46:52") ) ;
		newEntity.setOrganisationId( Integer.valueOf(100) ) ;

		// save entity in database
        em.getTransaction().begin();
        Datalog managedEntity = (Datalog) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Datalog getEntity() {
    	return entity;
    }
}
