/*
 * Created on 2022-01-04 ( 14:24:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Customerinfo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="customerinfo", schema="public" )
public class Customerinfo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="customerid", nullable=false)
    private Integer    customerid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="address1", length=2147483647)
    private String     address1 ;

    @Column(name="address2", length=2147483647)
    private String     address2 ;

    @Column(name="address3", length=2147483647)
    private String     address3 ;

    @Column(name="address4", length=2147483647)
    private String     address4 ;

    @Column(name="agegroup")
    private Integer    agegroup ;

    @Column(name="bddiscountused")
    private Integer    bddiscountused ;

    @Column(name="cardtype", length=2147483647)
    private String     cardtype ;

    @Column(name="christianname", length=2147483647)
    private String     christianname ;

    @Column(name="cobrandcardnumber")
    private Integer    cobrandcardnumber ;

    @Column(name="communicationmode")
    private Integer    communicationmode ;

    @Column(name="country", length=2147483647)
    private String     country ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdatetime")
    private Date       createdatetime ;

    @Column(name="customercode", length=2147483647)
    private String     customercode ;

    @Column(name="customerinfostatus")
    private Integer    customerinfostatus ;

    @Column(name="customertype")
    private Integer    customertype ;

    @Column(name="discount")
    private Integer    discount ;

    @Temporal(TemporalType.DATE)
    @Column(name="dob", nullable=false)
    private Date       dob ;

    @Column(name="email", length=2147483647)
    private String     email ;

    @Temporal(TemporalType.DATE)
    @Column(name="expirydate")
    private Date       expirydate ;

    @Column(name="handphone", length=2147483647)
    private String     handphone ;

    @Column(name="homephone", length=2147483647)
    private String     homephone ;

    @Column(name="incomegroup")
    private Integer    incomegroup ;

    @Temporal(TemporalType.DATE)
    @Column(name="issuedate")
    private Date       issuedate ;

    @Temporal(TemporalType.DATE)
    @Column(name="joindate")
    private Date       joindate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lasteditdatetime")
    private Date       lasteditdatetime ;

    @Column(name="maritalstatus")
    private Integer    maritalstatus ;

    @Column(name="name", length=2147483647)
    private String     name ;

    @Column(name="nationality", length=2147483647)
    private String     nationality ;

    @Column(name="newcardtype")
    private Integer    newcardtype ;

    @Column(name="nric", length=2147483647)
    private String     nric ;

    @Column(name="occupation")
    private Integer    occupation ;

    @Column(name="officephone", length=2147483647)
    private String     officephone ;

    @Column(name="outlet")
    private Integer    outlet ;

    @Column(name="pinnumber", length=2147483647)
    private String     pinnumber ;

    @Column(name="pinstatus")
    private Integer    pinstatus ;

    @Column(name="postalcode", length=2147483647)
    private String     postalcode ;

    @Column(name="race", length=2147483647)
    private String     race ;

    @Column(name="remarks", length=2147483647)
    private String     remarks ;

    @Column(name="rewardpoint")
    private Double     rewardpoint ;

    @Column(name="salutation")
    private Integer    salutation ;

    @Column(name="sex", length=2147483647)
    private String     sex ;

    @Column(name="status")
    private Integer    status ;

    @Column(name="surname", length=2147483647)
    private String     surname ;

    @Column(name="disc_id")
    private Integer    discId ;

    @Column(name="cumulativebalancetodate")
    private Double     cumulativebalancetodate ;

    @Column(name="currentdaybalance")
    private Double     currentdaybalance ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastsalesupdate")
    private Date       lastsalesupdate ;

    @Lob
    @Column(name="picture")
    private byte[]     picture ;

    @Column(name="postalcode2")
    private Integer    postalcode2 ;

    @Column(name="country2", length=2147483647)
    private String     country2 ;

    @Column(name="password", length=2147483647)
    private String     password ;

    @Column(name="userlogin", length=2147483647)
    private String     userlogin ;

    @Column(name="field1", length=2147483647)
    private String     field1 ;

    @Column(name="field2", length=2147483647)
    private String     field2 ;

    @Column(name="field3", length=2147483647)
    private String     field3 ;

    @Column(name="field4", length=2147483647)
    private String     field4 ;

    @Column(name="field5", length=2147483647)
    private String     field5 ;

    @Column(name="field6", length=2147483647)
    private String     field6 ;

    @Column(name="field7", length=2147483647)
    private String     field7 ;

    @Column(name="field8", length=2147483647)
    private String     field8 ;

    @Column(name="field9", length=2147483647)
    private String     field9 ;

    @Column(name="field10", length=2147483647)
    private String     field10 ;

    @Column(name="company", length=2147483647)
    private String     company ;

    @Column(name="designation", length=2147483647)
    private String     designation ;

    @Column(name="currentrspoint")
    private Double     currentrspoint ;

    @Column(name="field11", length=2147483647)
    private String     field11 ;

    @Column(name="field12", length=2147483647)
    private String     field12 ;

    @Column(name="field13", length=2147483647)
    private String     field13 ;

    @Column(name="field14", length=2147483647)
    private String     field14 ;

    @Column(name="field15", length=2147483647)
    private String     field15 ;

    @Column(name="field16", length=2147483647)
    private String     field16 ;

    @Column(name="field17", length=2147483647)
    private String     field17 ;

    @Column(name="field18", length=2147483647)
    private String     field18 ;

    @Column(name="field19", length=2147483647)
    private String     field19 ;

    @Column(name="field20", length=2147483647)
    private String     field20 ;

    @Column(name="field21", length=2147483647)
    private String     field21 ;

    @Column(name="field22", length=2147483647)
    private String     field22 ;

    @Column(name="field23", length=2147483647)
    private String     field23 ;

    @Column(name="field24", length=2147483647)
    private String     field24 ;

    @Column(name="field25", length=2147483647)
    private String     field25 ;

    @Column(name="field26", length=2147483647)
    private String     field26 ;

    @Column(name="field27", length=2147483647)
    private String     field27 ;

    @Column(name="field28", length=2147483647)
    private String     field28 ;

    @Column(name="field29", length=2147483647)
    private String     field29 ;

    @Column(name="field30", length=2147483647)
    private String     field30 ;

    @Column(name="field31", length=2147483647)
    private String     field31 ;

    @Column(name="field32", length=2147483647)
    private String     field32 ;

    @Column(name="field33", length=2147483647)
    private String     field33 ;

    @Column(name="field34", length=2147483647)
    private String     field34 ;

    @Column(name="field35", length=2147483647)
    private String     field35 ;

    @Column(name="field36", length=2147483647)
    private String     field36 ;

    @Column(name="field37", length=2147483647)
    private String     field37 ;

    @Column(name="field38", length=2147483647)
    private String     field38 ;

    @Column(name="field39", length=2147483647)
    private String     field39 ;

    @Column(name="field40", length=2147483647)
    private String     field40 ;

    @Column(name="field41", length=2147483647)
    private String     field41 ;

    @Column(name="field42", length=2147483647)
    private String     field42 ;

    @Column(name="field43", length=2147483647)
    private String     field43 ;

    @Column(name="field44", length=2147483647)
    private String     field44 ;

    @Column(name="field45", length=2147483647)
    private String     field45 ;

    @Column(name="field46", length=2147483647)
    private String     field46 ;

    @Column(name="field47", length=2147483647)
    private String     field47 ;

    @Column(name="field48", length=2147483647)
    private String     field48 ;

    @Column(name="field49", length=2147483647)
    private String     field49 ;

    @Column(name="field50", length=2147483647)
    private String     field50 ;

    @Column(name="shippingaddress", length=2147483647)
    private String     shippingaddress ;

    @Column(name="shippingaddress2", length=2147483647)
    private String     shippingaddress2 ;

    @Column(name="shippingpostalcode", length=2147483647)
    private String     shippingpostalcode ;

    @Column(name="shippingcountry", length=2147483647)
    private String     shippingcountry ;

    @Column(name="username", length=255)
    private String     username ;

    @Column(name="activationcode", length=100)
    private String     activationcode ;

    @Column(name="picture_name", length=2147483647)
    private String     pictureName ;

    @Column(name="contacted")
    private Boolean    contacted ;

    @Column(name="contactedsms")
    private Boolean    contactedsms ;

    @Column(name="contactedemail")
    private Boolean    contactedemail ;

    @Column(name="contactedcall")
    private Boolean    contactedcall ;

    @Column(name="shoesize")
    private Integer    shoesize ;

    @Column(name="interest")
    private Integer    interest ;

    @Column(name="childname1", length=2147483647)
    private String     childname1 ;

    @Temporal(TemporalType.DATE)
    @Column(name="childdob1")
    private Date       childdob1 ;

    @Column(name="childsex1", length=2147483647)
    private String     childsex1 ;

    @Column(name="childname2", length=2147483647)
    private String     childname2 ;

    @Temporal(TemporalType.DATE)
    @Column(name="childdob2")
    private Date       childdob2 ;

    @Column(name="childsex2", length=2147483647)
    private String     childsex2 ;

    @Column(name="childname3", length=2147483647)
    private String     childname3 ;

    @Temporal(TemporalType.DATE)
    @Column(name="childdob3")
    private Date       childdob3 ;

    @Column(name="childsex3", length=2147483647)
    private String     childsex3 ;

    @Column(name="customstyle")
    private Integer    customstyle ;

    @Column(name="customsize", length=2147483647)
    private String     customsize ;

    @Column(name="otherinterest", length=2147483647)
    private String     otherinterest ;

    @Column(name="haschildren")
    private Boolean    haschildren ;

    @Column(name="sizeid")
    private Integer    sizeid ;

    @Column(name="nationalityid")
    private Integer    nationalityid ;

    @Column(name="creditlimit")
    private Double     creditlimit ;

    @Column(name="creditbuffer")
    private Double     creditbuffer ;

    @Column(name="shippingcity", length=2147483647)
    private String     shippingcity ;

    @Column(name="shippingcontact", length=2147483647)
    private String     shippingcontact ;

    @Column(name="countrycode", length=2147483647)
    private String     countrycode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_upgraded_date")
    private Date       lastUpgradedDate ;

    @Column(name="organisation_id")
    private Integer    organisationId ;

    @Column(name="sync_app", length=2147483647)
    private String     syncApp ;

    @Column(name="sync_customer_id", length=2147483647)
    private String     syncCustomerId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_before_lastupdatemembership")
    private Date       dateBeforeLastupdatemembership ;

    @Column(name="custtype_before_lastupdatemembership")
    private Integer    custtypeBeforeLastupdatemembership ;

    @Column(name="customnumber", length=2147483647)
    private String     customnumber ;

    @Column(name="membershipcode", length=2147483647)
    private String     membershipcode ;

    @Column(name="allmergecustomer", length=2147483647)
    private String     allmergecustomer ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="window_start")
    private Date       windowStart ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="window_end")
    private Date       windowEnd ;

    @Column(name="register_type", length=2147483647)
    private String     registerType ;

    @Column(name="referred_salesman", length=2147483647)
    private String     referredSalesman ;

    @Column(name="referred_userid")
    private Integer    referredUserid ;

    @Column(name="customerpoints")
    private Double     customerpoints ;

    @Column(name="race_id")
    private Integer    raceId ;

    @Column(name="vip_press_value")
    private Double     vipPressValue ;

    @Column(name="vip_media_value")
    private Double     vipMediaValue ;

    @Column(name="taobaonick", length=2147483647)
    private String     taobaonick ;

    @Column(name="customerdepid", length=2147483647)
    private String     customerdepid ;

    @Column(name="customer_mode")
    private Integer    customerMode ;

    @Column(name="wechat_openid", length=2147483647)
    private String     wechatOpenid ;

    @Column(name="customer_interest", length=2147483647)
    private String     customerInterest ;

    @Column(name="customer_hobbies", length=2147483647)
    private String     customerHobbies ;

    @Column(name="customerinfo_group1_id")
    private Integer    customerinfoGroup1Id ;

    @Column(name="customerinfo_group2_id")
    private Integer    customerinfoGroup2Id ;

    @Column(name="activity_status", length=2147483647)
    private String     activityStatus ;

    @Column(name="external_reference", length=2147483647)
    private String     externalReference ;

    @Column(name="terms_of_payment_id")
    private Integer    termsOfPaymentId ;

    @Column(name="terms_of_payment", length=2147483647)
    private String     termsOfPayment ;

    @Column(name="city", length=2147483647)
    private String     city ;

    @Column(name="shippingcontact_number", length=2147483647)
    private String     shippingcontactNumber ;

    @Column(name="tax_identification_number", length=2147483647)
    private String     taxIdentificationNumber ;

    @Column(name="contact_by_telegram")
    private Boolean    contactByTelegram ;

    @Column(name="contact_by_wechat")
    private Boolean    contactByWechat ;

    @Column(name="contact_by_whatsapp")
    private Boolean    contactByWhatsapp ;

    @Column(name="contact_by_line")
    private Boolean    contactByLine ;

    @Column(name="contact_by_line_reference_id", length=2147483647)
    private String     contactByLineReferenceId ;

    @Column(name="contact_by_whatsapp_reference_id", length=2147483647)
    private String     contactByWhatsappReferenceId ;

    @Column(name="contact_by_wechat_reference_id", length=2147483647)
    private String     contactByWechatReferenceId ;

    @Column(name="contact_by_telegram_reference_id", length=2147483647)
    private String     contactByTelegramReferenceId ;

    @Column(name="agree_for_registration")
    private Integer    agreeForRegistration ;

    @Column(name="taxgroup")
    private Integer    taxgroup ;

    @Column(name="customer_uuid", length=2147483647)
    private String     customerUuid ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Customerinfo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setCustomerid( Integer customerid ) {
        this.customerid = customerid ;
    }
    public Integer getCustomerid() {
        return this.customerid;
    }

    public void setAddress1( String address1 ) {
        this.address1 = address1 ;
    }
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress2( String address2 ) {
        this.address2 = address2 ;
    }
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress3( String address3 ) {
        this.address3 = address3 ;
    }
    public String getAddress3() {
        return this.address3;
    }

    public void setAddress4( String address4 ) {
        this.address4 = address4 ;
    }
    public String getAddress4() {
        return this.address4;
    }

    public void setAgegroup( Integer agegroup ) {
        this.agegroup = agegroup ;
    }
    public Integer getAgegroup() {
        return this.agegroup;
    }

    public void setBddiscountused( Integer bddiscountused ) {
        this.bddiscountused = bddiscountused ;
    }
    public Integer getBddiscountused() {
        return this.bddiscountused;
    }

    public void setCardtype( String cardtype ) {
        this.cardtype = cardtype ;
    }
    public String getCardtype() {
        return this.cardtype;
    }

    public void setChristianname( String christianname ) {
        this.christianname = christianname ;
    }
    public String getChristianname() {
        return this.christianname;
    }

    public void setCobrandcardnumber( Integer cobrandcardnumber ) {
        this.cobrandcardnumber = cobrandcardnumber ;
    }
    public Integer getCobrandcardnumber() {
        return this.cobrandcardnumber;
    }

    public void setCommunicationmode( Integer communicationmode ) {
        this.communicationmode = communicationmode ;
    }
    public Integer getCommunicationmode() {
        return this.communicationmode;
    }

    public void setCountry( String country ) {
        this.country = country ;
    }
    public String getCountry() {
        return this.country;
    }

    public void setCreatedatetime( Date createdatetime ) {
        this.createdatetime = createdatetime ;
    }
    public Date getCreatedatetime() {
        return this.createdatetime;
    }

    public void setCustomercode( String customercode ) {
        this.customercode = customercode ;
    }
    public String getCustomercode() {
        return this.customercode;
    }

    public void setCustomerinfostatus( Integer customerinfostatus ) {
        this.customerinfostatus = customerinfostatus ;
    }
    public Integer getCustomerinfostatus() {
        return this.customerinfostatus;
    }

    public void setCustomertype( Integer customertype ) {
        this.customertype = customertype ;
    }
    public Integer getCustomertype() {
        return this.customertype;
    }

    public void setDiscount( Integer discount ) {
        this.discount = discount ;
    }
    public Integer getDiscount() {
        return this.discount;
    }

    public void setDob( Date dob ) {
        this.dob = dob ;
    }
    public Date getDob() {
        return this.dob;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setExpirydate( Date expirydate ) {
        this.expirydate = expirydate ;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }

    public void setHandphone( String handphone ) {
        this.handphone = handphone ;
    }
    public String getHandphone() {
        return this.handphone;
    }

    public void setHomephone( String homephone ) {
        this.homephone = homephone ;
    }
    public String getHomephone() {
        return this.homephone;
    }

    public void setIncomegroup( Integer incomegroup ) {
        this.incomegroup = incomegroup ;
    }
    public Integer getIncomegroup() {
        return this.incomegroup;
    }

    public void setIssuedate( Date issuedate ) {
        this.issuedate = issuedate ;
    }
    public Date getIssuedate() {
        return this.issuedate;
    }

    public void setJoindate( Date joindate ) {
        this.joindate = joindate ;
    }
    public Date getJoindate() {
        return this.joindate;
    }

    public void setLasteditdatetime( Date lasteditdatetime ) {
        this.lasteditdatetime = lasteditdatetime ;
    }
    public Date getLasteditdatetime() {
        return this.lasteditdatetime;
    }

    public void setMaritalstatus( Integer maritalstatus ) {
        this.maritalstatus = maritalstatus ;
    }
    public Integer getMaritalstatus() {
        return this.maritalstatus;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setNationality( String nationality ) {
        this.nationality = nationality ;
    }
    public String getNationality() {
        return this.nationality;
    }

    public void setNewcardtype( Integer newcardtype ) {
        this.newcardtype = newcardtype ;
    }
    public Integer getNewcardtype() {
        return this.newcardtype;
    }

    public void setNric( String nric ) {
        this.nric = nric ;
    }
    public String getNric() {
        return this.nric;
    }

    public void setOccupation( Integer occupation ) {
        this.occupation = occupation ;
    }
    public Integer getOccupation() {
        return this.occupation;
    }

    public void setOfficephone( String officephone ) {
        this.officephone = officephone ;
    }
    public String getOfficephone() {
        return this.officephone;
    }

    public void setOutlet( Integer outlet ) {
        this.outlet = outlet ;
    }
    public Integer getOutlet() {
        return this.outlet;
    }

    public void setPinnumber( String pinnumber ) {
        this.pinnumber = pinnumber ;
    }
    public String getPinnumber() {
        return this.pinnumber;
    }

    public void setPinstatus( Integer pinstatus ) {
        this.pinstatus = pinstatus ;
    }
    public Integer getPinstatus() {
        return this.pinstatus;
    }

    public void setPostalcode( String postalcode ) {
        this.postalcode = postalcode ;
    }
    public String getPostalcode() {
        return this.postalcode;
    }

    public void setRace( String race ) {
        this.race = race ;
    }
    public String getRace() {
        return this.race;
    }

    public void setRemarks( String remarks ) {
        this.remarks = remarks ;
    }
    public String getRemarks() {
        return this.remarks;
    }

    public void setRewardpoint( Double rewardpoint ) {
        this.rewardpoint = rewardpoint ;
    }
    public Double getRewardpoint() {
        return this.rewardpoint;
    }

    public void setSalutation( Integer salutation ) {
        this.salutation = salutation ;
    }
    public Integer getSalutation() {
        return this.salutation;
    }

    public void setSex( String sex ) {
        this.sex = sex ;
    }
    public String getSex() {
        return this.sex;
    }

    public void setStatus( Integer status ) {
        this.status = status ;
    }
    public Integer getStatus() {
        return this.status;
    }

    public void setSurname( String surname ) {
        this.surname = surname ;
    }
    public String getSurname() {
        return this.surname;
    }

    public void setDiscId( Integer discId ) {
        this.discId = discId ;
    }
    public Integer getDiscId() {
        return this.discId;
    }

    public void setCumulativebalancetodate( Double cumulativebalancetodate ) {
        this.cumulativebalancetodate = cumulativebalancetodate ;
    }
    public Double getCumulativebalancetodate() {
        return this.cumulativebalancetodate;
    }

    public void setCurrentdaybalance( Double currentdaybalance ) {
        this.currentdaybalance = currentdaybalance ;
    }
    public Double getCurrentdaybalance() {
        return this.currentdaybalance;
    }

    public void setLastsalesupdate( Date lastsalesupdate ) {
        this.lastsalesupdate = lastsalesupdate ;
    }
    public Date getLastsalesupdate() {
        return this.lastsalesupdate;
    }

    public void setPicture( byte[] picture ) {
        this.picture = picture ;
    }
    public byte[] getPicture() {
        return this.picture;
    }

    public void setPostalcode2( Integer postalcode2 ) {
        this.postalcode2 = postalcode2 ;
    }
    public Integer getPostalcode2() {
        return this.postalcode2;
    }

    public void setCountry2( String country2 ) {
        this.country2 = country2 ;
    }
    public String getCountry2() {
        return this.country2;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    public void setUserlogin( String userlogin ) {
        this.userlogin = userlogin ;
    }
    public String getUserlogin() {
        return this.userlogin;
    }

    public void setField1( String field1 ) {
        this.field1 = field1 ;
    }
    public String getField1() {
        return this.field1;
    }

    public void setField2( String field2 ) {
        this.field2 = field2 ;
    }
    public String getField2() {
        return this.field2;
    }

    public void setField3( String field3 ) {
        this.field3 = field3 ;
    }
    public String getField3() {
        return this.field3;
    }

    public void setField4( String field4 ) {
        this.field4 = field4 ;
    }
    public String getField4() {
        return this.field4;
    }

    public void setField5( String field5 ) {
        this.field5 = field5 ;
    }
    public String getField5() {
        return this.field5;
    }

    public void setField6( String field6 ) {
        this.field6 = field6 ;
    }
    public String getField6() {
        return this.field6;
    }

    public void setField7( String field7 ) {
        this.field7 = field7 ;
    }
    public String getField7() {
        return this.field7;
    }

    public void setField8( String field8 ) {
        this.field8 = field8 ;
    }
    public String getField8() {
        return this.field8;
    }

    public void setField9( String field9 ) {
        this.field9 = field9 ;
    }
    public String getField9() {
        return this.field9;
    }

    public void setField10( String field10 ) {
        this.field10 = field10 ;
    }
    public String getField10() {
        return this.field10;
    }

    public void setCompany( String company ) {
        this.company = company ;
    }
    public String getCompany() {
        return this.company;
    }

    public void setDesignation( String designation ) {
        this.designation = designation ;
    }
    public String getDesignation() {
        return this.designation;
    }

    public void setCurrentrspoint( Double currentrspoint ) {
        this.currentrspoint = currentrspoint ;
    }
    public Double getCurrentrspoint() {
        return this.currentrspoint;
    }

    public void setField11( String field11 ) {
        this.field11 = field11 ;
    }
    public String getField11() {
        return this.field11;
    }

    public void setField12( String field12 ) {
        this.field12 = field12 ;
    }
    public String getField12() {
        return this.field12;
    }

    public void setField13( String field13 ) {
        this.field13 = field13 ;
    }
    public String getField13() {
        return this.field13;
    }

    public void setField14( String field14 ) {
        this.field14 = field14 ;
    }
    public String getField14() {
        return this.field14;
    }

    public void setField15( String field15 ) {
        this.field15 = field15 ;
    }
    public String getField15() {
        return this.field15;
    }

    public void setField16( String field16 ) {
        this.field16 = field16 ;
    }
    public String getField16() {
        return this.field16;
    }

    public void setField17( String field17 ) {
        this.field17 = field17 ;
    }
    public String getField17() {
        return this.field17;
    }

    public void setField18( String field18 ) {
        this.field18 = field18 ;
    }
    public String getField18() {
        return this.field18;
    }

    public void setField19( String field19 ) {
        this.field19 = field19 ;
    }
    public String getField19() {
        return this.field19;
    }

    public void setField20( String field20 ) {
        this.field20 = field20 ;
    }
    public String getField20() {
        return this.field20;
    }

    public void setField21( String field21 ) {
        this.field21 = field21 ;
    }
    public String getField21() {
        return this.field21;
    }

    public void setField22( String field22 ) {
        this.field22 = field22 ;
    }
    public String getField22() {
        return this.field22;
    }

    public void setField23( String field23 ) {
        this.field23 = field23 ;
    }
    public String getField23() {
        return this.field23;
    }

    public void setField24( String field24 ) {
        this.field24 = field24 ;
    }
    public String getField24() {
        return this.field24;
    }

    public void setField25( String field25 ) {
        this.field25 = field25 ;
    }
    public String getField25() {
        return this.field25;
    }

    public void setField26( String field26 ) {
        this.field26 = field26 ;
    }
    public String getField26() {
        return this.field26;
    }

    public void setField27( String field27 ) {
        this.field27 = field27 ;
    }
    public String getField27() {
        return this.field27;
    }

    public void setField28( String field28 ) {
        this.field28 = field28 ;
    }
    public String getField28() {
        return this.field28;
    }

    public void setField29( String field29 ) {
        this.field29 = field29 ;
    }
    public String getField29() {
        return this.field29;
    }

    public void setField30( String field30 ) {
        this.field30 = field30 ;
    }
    public String getField30() {
        return this.field30;
    }

    public void setField31( String field31 ) {
        this.field31 = field31 ;
    }
    public String getField31() {
        return this.field31;
    }

    public void setField32( String field32 ) {
        this.field32 = field32 ;
    }
    public String getField32() {
        return this.field32;
    }

    public void setField33( String field33 ) {
        this.field33 = field33 ;
    }
    public String getField33() {
        return this.field33;
    }

    public void setField34( String field34 ) {
        this.field34 = field34 ;
    }
    public String getField34() {
        return this.field34;
    }

    public void setField35( String field35 ) {
        this.field35 = field35 ;
    }
    public String getField35() {
        return this.field35;
    }

    public void setField36( String field36 ) {
        this.field36 = field36 ;
    }
    public String getField36() {
        return this.field36;
    }

    public void setField37( String field37 ) {
        this.field37 = field37 ;
    }
    public String getField37() {
        return this.field37;
    }

    public void setField38( String field38 ) {
        this.field38 = field38 ;
    }
    public String getField38() {
        return this.field38;
    }

    public void setField39( String field39 ) {
        this.field39 = field39 ;
    }
    public String getField39() {
        return this.field39;
    }

    public void setField40( String field40 ) {
        this.field40 = field40 ;
    }
    public String getField40() {
        return this.field40;
    }

    public void setField41( String field41 ) {
        this.field41 = field41 ;
    }
    public String getField41() {
        return this.field41;
    }

    public void setField42( String field42 ) {
        this.field42 = field42 ;
    }
    public String getField42() {
        return this.field42;
    }

    public void setField43( String field43 ) {
        this.field43 = field43 ;
    }
    public String getField43() {
        return this.field43;
    }

    public void setField44( String field44 ) {
        this.field44 = field44 ;
    }
    public String getField44() {
        return this.field44;
    }

    public void setField45( String field45 ) {
        this.field45 = field45 ;
    }
    public String getField45() {
        return this.field45;
    }

    public void setField46( String field46 ) {
        this.field46 = field46 ;
    }
    public String getField46() {
        return this.field46;
    }

    public void setField47( String field47 ) {
        this.field47 = field47 ;
    }
    public String getField47() {
        return this.field47;
    }

    public void setField48( String field48 ) {
        this.field48 = field48 ;
    }
    public String getField48() {
        return this.field48;
    }

    public void setField49( String field49 ) {
        this.field49 = field49 ;
    }
    public String getField49() {
        return this.field49;
    }

    public void setField50( String field50 ) {
        this.field50 = field50 ;
    }
    public String getField50() {
        return this.field50;
    }

    public void setShippingaddress( String shippingaddress ) {
        this.shippingaddress = shippingaddress ;
    }
    public String getShippingaddress() {
        return this.shippingaddress;
    }

    public void setShippingaddress2( String shippingaddress2 ) {
        this.shippingaddress2 = shippingaddress2 ;
    }
    public String getShippingaddress2() {
        return this.shippingaddress2;
    }

    public void setShippingpostalcode( String shippingpostalcode ) {
        this.shippingpostalcode = shippingpostalcode ;
    }
    public String getShippingpostalcode() {
        return this.shippingpostalcode;
    }

    public void setShippingcountry( String shippingcountry ) {
        this.shippingcountry = shippingcountry ;
    }
    public String getShippingcountry() {
        return this.shippingcountry;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setActivationcode( String activationcode ) {
        this.activationcode = activationcode ;
    }
    public String getActivationcode() {
        return this.activationcode;
    }

    public void setPictureName( String pictureName ) {
        this.pictureName = pictureName ;
    }
    public String getPictureName() {
        return this.pictureName;
    }

    public void setContacted( Boolean contacted ) {
        this.contacted = contacted ;
    }
    public Boolean getContacted() {
        return this.contacted;
    }

    public void setContactedsms( Boolean contactedsms ) {
        this.contactedsms = contactedsms ;
    }
    public Boolean getContactedsms() {
        return this.contactedsms;
    }

    public void setContactedemail( Boolean contactedemail ) {
        this.contactedemail = contactedemail ;
    }
    public Boolean getContactedemail() {
        return this.contactedemail;
    }

    public void setContactedcall( Boolean contactedcall ) {
        this.contactedcall = contactedcall ;
    }
    public Boolean getContactedcall() {
        return this.contactedcall;
    }

    public void setShoesize( Integer shoesize ) {
        this.shoesize = shoesize ;
    }
    public Integer getShoesize() {
        return this.shoesize;
    }

    public void setInterest( Integer interest ) {
        this.interest = interest ;
    }
    public Integer getInterest() {
        return this.interest;
    }

    public void setChildname1( String childname1 ) {
        this.childname1 = childname1 ;
    }
    public String getChildname1() {
        return this.childname1;
    }

    public void setChilddob1( Date childdob1 ) {
        this.childdob1 = childdob1 ;
    }
    public Date getChilddob1() {
        return this.childdob1;
    }

    public void setChildsex1( String childsex1 ) {
        this.childsex1 = childsex1 ;
    }
    public String getChildsex1() {
        return this.childsex1;
    }

    public void setChildname2( String childname2 ) {
        this.childname2 = childname2 ;
    }
    public String getChildname2() {
        return this.childname2;
    }

    public void setChilddob2( Date childdob2 ) {
        this.childdob2 = childdob2 ;
    }
    public Date getChilddob2() {
        return this.childdob2;
    }

    public void setChildsex2( String childsex2 ) {
        this.childsex2 = childsex2 ;
    }
    public String getChildsex2() {
        return this.childsex2;
    }

    public void setChildname3( String childname3 ) {
        this.childname3 = childname3 ;
    }
    public String getChildname3() {
        return this.childname3;
    }

    public void setChilddob3( Date childdob3 ) {
        this.childdob3 = childdob3 ;
    }
    public Date getChilddob3() {
        return this.childdob3;
    }

    public void setChildsex3( String childsex3 ) {
        this.childsex3 = childsex3 ;
    }
    public String getChildsex3() {
        return this.childsex3;
    }

    public void setCustomstyle( Integer customstyle ) {
        this.customstyle = customstyle ;
    }
    public Integer getCustomstyle() {
        return this.customstyle;
    }

    public void setCustomsize( String customsize ) {
        this.customsize = customsize ;
    }
    public String getCustomsize() {
        return this.customsize;
    }

    public void setOtherinterest( String otherinterest ) {
        this.otherinterest = otherinterest ;
    }
    public String getOtherinterest() {
        return this.otherinterest;
    }

    public void setHaschildren( Boolean haschildren ) {
        this.haschildren = haschildren ;
    }
    public Boolean getHaschildren() {
        return this.haschildren;
    }

    public void setSizeid( Integer sizeid ) {
        this.sizeid = sizeid ;
    }
    public Integer getSizeid() {
        return this.sizeid;
    }

    public void setNationalityid( Integer nationalityid ) {
        this.nationalityid = nationalityid ;
    }
    public Integer getNationalityid() {
        return this.nationalityid;
    }

    public void setCreditlimit( Double creditlimit ) {
        this.creditlimit = creditlimit ;
    }
    public Double getCreditlimit() {
        return this.creditlimit;
    }

    public void setCreditbuffer( Double creditbuffer ) {
        this.creditbuffer = creditbuffer ;
    }
    public Double getCreditbuffer() {
        return this.creditbuffer;
    }

    public void setShippingcity( String shippingcity ) {
        this.shippingcity = shippingcity ;
    }
    public String getShippingcity() {
        return this.shippingcity;
    }

    public void setShippingcontact( String shippingcontact ) {
        this.shippingcontact = shippingcontact ;
    }
    public String getShippingcontact() {
        return this.shippingcontact;
    }

    public void setCountrycode( String countrycode ) {
        this.countrycode = countrycode ;
    }
    public String getCountrycode() {
        return this.countrycode;
    }

    public void setLastUpgradedDate( Date lastUpgradedDate ) {
        this.lastUpgradedDate = lastUpgradedDate ;
    }
    public Date getLastUpgradedDate() {
        return this.lastUpgradedDate;
    }

    public void setOrganisationId( Integer organisationId ) {
        this.organisationId = organisationId ;
    }
    public Integer getOrganisationId() {
        return this.organisationId;
    }

    public void setSyncApp( String syncApp ) {
        this.syncApp = syncApp ;
    }
    public String getSyncApp() {
        return this.syncApp;
    }

    public void setSyncCustomerId( String syncCustomerId ) {
        this.syncCustomerId = syncCustomerId ;
    }
    public String getSyncCustomerId() {
        return this.syncCustomerId;
    }

    public void setDateBeforeLastupdatemembership( Date dateBeforeLastupdatemembership ) {
        this.dateBeforeLastupdatemembership = dateBeforeLastupdatemembership ;
    }
    public Date getDateBeforeLastupdatemembership() {
        return this.dateBeforeLastupdatemembership;
    }

    public void setCusttypeBeforeLastupdatemembership( Integer custtypeBeforeLastupdatemembership ) {
        this.custtypeBeforeLastupdatemembership = custtypeBeforeLastupdatemembership ;
    }
    public Integer getCusttypeBeforeLastupdatemembership() {
        return this.custtypeBeforeLastupdatemembership;
    }

    public void setCustomnumber( String customnumber ) {
        this.customnumber = customnumber ;
    }
    public String getCustomnumber() {
        return this.customnumber;
    }

    public void setMembershipcode( String membershipcode ) {
        this.membershipcode = membershipcode ;
    }
    public String getMembershipcode() {
        return this.membershipcode;
    }

    public void setAllmergecustomer( String allmergecustomer ) {
        this.allmergecustomer = allmergecustomer ;
    }
    public String getAllmergecustomer() {
        return this.allmergecustomer;
    }

    public void setWindowStart( Date windowStart ) {
        this.windowStart = windowStart ;
    }
    public Date getWindowStart() {
        return this.windowStart;
    }

    public void setWindowEnd( Date windowEnd ) {
        this.windowEnd = windowEnd ;
    }
    public Date getWindowEnd() {
        return this.windowEnd;
    }

    public void setRegisterType( String registerType ) {
        this.registerType = registerType ;
    }
    public String getRegisterType() {
        return this.registerType;
    }

    public void setReferredSalesman( String referredSalesman ) {
        this.referredSalesman = referredSalesman ;
    }
    public String getReferredSalesman() {
        return this.referredSalesman;
    }

    public void setReferredUserid( Integer referredUserid ) {
        this.referredUserid = referredUserid ;
    }
    public Integer getReferredUserid() {
        return this.referredUserid;
    }

    public void setCustomerpoints( Double customerpoints ) {
        this.customerpoints = customerpoints ;
    }
    public Double getCustomerpoints() {
        return this.customerpoints;
    }

    public void setRaceId( Integer raceId ) {
        this.raceId = raceId ;
    }
    public Integer getRaceId() {
        return this.raceId;
    }

    public void setVipPressValue( Double vipPressValue ) {
        this.vipPressValue = vipPressValue ;
    }
    public Double getVipPressValue() {
        return this.vipPressValue;
    }

    public void setVipMediaValue( Double vipMediaValue ) {
        this.vipMediaValue = vipMediaValue ;
    }
    public Double getVipMediaValue() {
        return this.vipMediaValue;
    }

    public void setTaobaonick( String taobaonick ) {
        this.taobaonick = taobaonick ;
    }
    public String getTaobaonick() {
        return this.taobaonick;
    }

    public void setCustomerdepid( String customerdepid ) {
        this.customerdepid = customerdepid ;
    }
    public String getCustomerdepid() {
        return this.customerdepid;
    }

    public void setCustomerMode( Integer customerMode ) {
        this.customerMode = customerMode ;
    }
    public Integer getCustomerMode() {
        return this.customerMode;
    }

    public void setWechatOpenid( String wechatOpenid ) {
        this.wechatOpenid = wechatOpenid ;
    }
    public String getWechatOpenid() {
        return this.wechatOpenid;
    }

    public void setCustomerInterest( String customerInterest ) {
        this.customerInterest = customerInterest ;
    }
    public String getCustomerInterest() {
        return this.customerInterest;
    }

    public void setCustomerHobbies( String customerHobbies ) {
        this.customerHobbies = customerHobbies ;
    }
    public String getCustomerHobbies() {
        return this.customerHobbies;
    }

    public void setCustomerinfoGroup1Id( Integer customerinfoGroup1Id ) {
        this.customerinfoGroup1Id = customerinfoGroup1Id ;
    }
    public Integer getCustomerinfoGroup1Id() {
        return this.customerinfoGroup1Id;
    }

    public void setCustomerinfoGroup2Id( Integer customerinfoGroup2Id ) {
        this.customerinfoGroup2Id = customerinfoGroup2Id ;
    }
    public Integer getCustomerinfoGroup2Id() {
        return this.customerinfoGroup2Id;
    }

    public void setActivityStatus( String activityStatus ) {
        this.activityStatus = activityStatus ;
    }
    public String getActivityStatus() {
        return this.activityStatus;
    }

    public void setExternalReference( String externalReference ) {
        this.externalReference = externalReference ;
    }
    public String getExternalReference() {
        return this.externalReference;
    }

    public void setTermsOfPaymentId( Integer termsOfPaymentId ) {
        this.termsOfPaymentId = termsOfPaymentId ;
    }
    public Integer getTermsOfPaymentId() {
        return this.termsOfPaymentId;
    }

    public void setTermsOfPayment( String termsOfPayment ) {
        this.termsOfPayment = termsOfPayment ;
    }
    public String getTermsOfPayment() {
        return this.termsOfPayment;
    }

    public void setCity( String city ) {
        this.city = city ;
    }
    public String getCity() {
        return this.city;
    }

    public void setShippingcontactNumber( String shippingcontactNumber ) {
        this.shippingcontactNumber = shippingcontactNumber ;
    }
    public String getShippingcontactNumber() {
        return this.shippingcontactNumber;
    }

    public void setTaxIdentificationNumber( String taxIdentificationNumber ) {
        this.taxIdentificationNumber = taxIdentificationNumber ;
    }
    public String getTaxIdentificationNumber() {
        return this.taxIdentificationNumber;
    }

    public void setContactByTelegram( Boolean contactByTelegram ) {
        this.contactByTelegram = contactByTelegram ;
    }
    public Boolean getContactByTelegram() {
        return this.contactByTelegram;
    }

    public void setContactByWechat( Boolean contactByWechat ) {
        this.contactByWechat = contactByWechat ;
    }
    public Boolean getContactByWechat() {
        return this.contactByWechat;
    }

    public void setContactByWhatsapp( Boolean contactByWhatsapp ) {
        this.contactByWhatsapp = contactByWhatsapp ;
    }
    public Boolean getContactByWhatsapp() {
        return this.contactByWhatsapp;
    }

    public void setContactByLine( Boolean contactByLine ) {
        this.contactByLine = contactByLine ;
    }
    public Boolean getContactByLine() {
        return this.contactByLine;
    }

    public void setContactByLineReferenceId( String contactByLineReferenceId ) {
        this.contactByLineReferenceId = contactByLineReferenceId ;
    }
    public String getContactByLineReferenceId() {
        return this.contactByLineReferenceId;
    }

    public void setContactByWhatsappReferenceId( String contactByWhatsappReferenceId ) {
        this.contactByWhatsappReferenceId = contactByWhatsappReferenceId ;
    }
    public String getContactByWhatsappReferenceId() {
        return this.contactByWhatsappReferenceId;
    }

    public void setContactByWechatReferenceId( String contactByWechatReferenceId ) {
        this.contactByWechatReferenceId = contactByWechatReferenceId ;
    }
    public String getContactByWechatReferenceId() {
        return this.contactByWechatReferenceId;
    }

    public void setContactByTelegramReferenceId( String contactByTelegramReferenceId ) {
        this.contactByTelegramReferenceId = contactByTelegramReferenceId ;
    }
    public String getContactByTelegramReferenceId() {
        return this.contactByTelegramReferenceId;
    }

    public void setAgreeForRegistration( Integer agreeForRegistration ) {
        this.agreeForRegistration = agreeForRegistration ;
    }
    public Integer getAgreeForRegistration() {
        return this.agreeForRegistration;
    }

    public void setTaxgroup( Integer taxgroup ) {
        this.taxgroup = taxgroup ;
    }
    public Integer getTaxgroup() {
        return this.taxgroup;
    }

    public void setCustomerUuid( String customerUuid ) {
        this.customerUuid = customerUuid ;
    }
    public String getCustomerUuid() {
        return this.customerUuid;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(customerid);
        sb.append("|");
        sb.append(address1);
        sb.append("|");
        sb.append(address2);
        sb.append("|");
        sb.append(address3);
        sb.append("|");
        sb.append(address4);
        sb.append("|");
        sb.append(agegroup);
        sb.append("|");
        sb.append(bddiscountused);
        sb.append("|");
        sb.append(cardtype);
        sb.append("|");
        sb.append(christianname);
        sb.append("|");
        sb.append(cobrandcardnumber);
        sb.append("|");
        sb.append(communicationmode);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(createdatetime);
        sb.append("|");
        sb.append(customercode);
        sb.append("|");
        sb.append(customerinfostatus);
        sb.append("|");
        sb.append(customertype);
        sb.append("|");
        sb.append(discount);
        sb.append("|");
        sb.append(dob);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(expirydate);
        sb.append("|");
        sb.append(handphone);
        sb.append("|");
        sb.append(homephone);
        sb.append("|");
        sb.append(incomegroup);
        sb.append("|");
        sb.append(issuedate);
        sb.append("|");
        sb.append(joindate);
        sb.append("|");
        sb.append(lasteditdatetime);
        sb.append("|");
        sb.append(maritalstatus);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(nationality);
        sb.append("|");
        sb.append(newcardtype);
        sb.append("|");
        sb.append(nric);
        sb.append("|");
        sb.append(occupation);
        sb.append("|");
        sb.append(officephone);
        sb.append("|");
        sb.append(outlet);
        sb.append("|");
        sb.append(pinnumber);
        sb.append("|");
        sb.append(pinstatus);
        sb.append("|");
        sb.append(postalcode);
        sb.append("|");
        sb.append(race);
        sb.append("|");
        sb.append(remarks);
        sb.append("|");
        sb.append(rewardpoint);
        sb.append("|");
        sb.append(salutation);
        sb.append("|");
        sb.append(sex);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(surname);
        sb.append("|");
        sb.append(discId);
        sb.append("|");
        sb.append(cumulativebalancetodate);
        sb.append("|");
        sb.append(currentdaybalance);
        sb.append("|");
        sb.append(lastsalesupdate);
        // attribute 'picture' not usable (type = byte[])
        sb.append("|");
        sb.append(postalcode2);
        sb.append("|");
        sb.append(country2);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(userlogin);
        sb.append("|");
        sb.append(field1);
        sb.append("|");
        sb.append(field2);
        sb.append("|");
        sb.append(field3);
        sb.append("|");
        sb.append(field4);
        sb.append("|");
        sb.append(field5);
        sb.append("|");
        sb.append(field6);
        sb.append("|");
        sb.append(field7);
        sb.append("|");
        sb.append(field8);
        sb.append("|");
        sb.append(field9);
        sb.append("|");
        sb.append(field10);
        sb.append("|");
        sb.append(company);
        sb.append("|");
        sb.append(designation);
        sb.append("|");
        sb.append(currentrspoint);
        sb.append("|");
        sb.append(field11);
        sb.append("|");
        sb.append(field12);
        sb.append("|");
        sb.append(field13);
        sb.append("|");
        sb.append(field14);
        sb.append("|");
        sb.append(field15);
        sb.append("|");
        sb.append(field16);
        sb.append("|");
        sb.append(field17);
        sb.append("|");
        sb.append(field18);
        sb.append("|");
        sb.append(field19);
        sb.append("|");
        sb.append(field20);
        sb.append("|");
        sb.append(field21);
        sb.append("|");
        sb.append(field22);
        sb.append("|");
        sb.append(field23);
        sb.append("|");
        sb.append(field24);
        sb.append("|");
        sb.append(field25);
        sb.append("|");
        sb.append(field26);
        sb.append("|");
        sb.append(field27);
        sb.append("|");
        sb.append(field28);
        sb.append("|");
        sb.append(field29);
        sb.append("|");
        sb.append(field30);
        sb.append("|");
        sb.append(field31);
        sb.append("|");
        sb.append(field32);
        sb.append("|");
        sb.append(field33);
        sb.append("|");
        sb.append(field34);
        sb.append("|");
        sb.append(field35);
        sb.append("|");
        sb.append(field36);
        sb.append("|");
        sb.append(field37);
        sb.append("|");
        sb.append(field38);
        sb.append("|");
        sb.append(field39);
        sb.append("|");
        sb.append(field40);
        sb.append("|");
        sb.append(field41);
        sb.append("|");
        sb.append(field42);
        sb.append("|");
        sb.append(field43);
        sb.append("|");
        sb.append(field44);
        sb.append("|");
        sb.append(field45);
        sb.append("|");
        sb.append(field46);
        sb.append("|");
        sb.append(field47);
        sb.append("|");
        sb.append(field48);
        sb.append("|");
        sb.append(field49);
        sb.append("|");
        sb.append(field50);
        sb.append("|");
        sb.append(shippingaddress);
        sb.append("|");
        sb.append(shippingaddress2);
        sb.append("|");
        sb.append(shippingpostalcode);
        sb.append("|");
        sb.append(shippingcountry);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(activationcode);
        sb.append("|");
        sb.append(pictureName);
        sb.append("|");
        sb.append(contacted);
        sb.append("|");
        sb.append(contactedsms);
        sb.append("|");
        sb.append(contactedemail);
        sb.append("|");
        sb.append(contactedcall);
        sb.append("|");
        sb.append(shoesize);
        sb.append("|");
        sb.append(interest);
        sb.append("|");
        sb.append(childname1);
        sb.append("|");
        sb.append(childdob1);
        sb.append("|");
        sb.append(childsex1);
        sb.append("|");
        sb.append(childname2);
        sb.append("|");
        sb.append(childdob2);
        sb.append("|");
        sb.append(childsex2);
        sb.append("|");
        sb.append(childname3);
        sb.append("|");
        sb.append(childdob3);
        sb.append("|");
        sb.append(childsex3);
        sb.append("|");
        sb.append(customstyle);
        sb.append("|");
        sb.append(customsize);
        sb.append("|");
        sb.append(otherinterest);
        sb.append("|");
        sb.append(haschildren);
        sb.append("|");
        sb.append(sizeid);
        sb.append("|");
        sb.append(nationalityid);
        sb.append("|");
        sb.append(creditlimit);
        sb.append("|");
        sb.append(creditbuffer);
        sb.append("|");
        sb.append(shippingcity);
        sb.append("|");
        sb.append(shippingcontact);
        sb.append("|");
        sb.append(countrycode);
        sb.append("|");
        sb.append(lastUpgradedDate);
        sb.append("|");
        sb.append(organisationId);
        sb.append("|");
        sb.append(syncApp);
        sb.append("|");
        sb.append(syncCustomerId);
        sb.append("|");
        sb.append(dateBeforeLastupdatemembership);
        sb.append("|");
        sb.append(custtypeBeforeLastupdatemembership);
        sb.append("|");
        sb.append(customnumber);
        sb.append("|");
        sb.append(membershipcode);
        sb.append("|");
        sb.append(allmergecustomer);
        sb.append("|");
        sb.append(windowStart);
        sb.append("|");
        sb.append(windowEnd);
        sb.append("|");
        sb.append(registerType);
        sb.append("|");
        sb.append(referredSalesman);
        sb.append("|");
        sb.append(referredUserid);
        sb.append("|");
        sb.append(customerpoints);
        sb.append("|");
        sb.append(raceId);
        sb.append("|");
        sb.append(vipPressValue);
        sb.append("|");
        sb.append(vipMediaValue);
        sb.append("|");
        sb.append(taobaonick);
        sb.append("|");
        sb.append(customerdepid);
        sb.append("|");
        sb.append(customerMode);
        sb.append("|");
        sb.append(wechatOpenid);
        sb.append("|");
        sb.append(customerInterest);
        sb.append("|");
        sb.append(customerHobbies);
        sb.append("|");
        sb.append(customerinfoGroup1Id);
        sb.append("|");
        sb.append(customerinfoGroup2Id);
        sb.append("|");
        sb.append(activityStatus);
        sb.append("|");
        sb.append(externalReference);
        sb.append("|");
        sb.append(termsOfPaymentId);
        sb.append("|");
        sb.append(termsOfPayment);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(shippingcontactNumber);
        sb.append("|");
        sb.append(taxIdentificationNumber);
        sb.append("|");
        sb.append(contactByTelegram);
        sb.append("|");
        sb.append(contactByWechat);
        sb.append("|");
        sb.append(contactByWhatsapp);
        sb.append("|");
        sb.append(contactByLine);
        sb.append("|");
        sb.append(contactByLineReferenceId);
        sb.append("|");
        sb.append(contactByWhatsappReferenceId);
        sb.append("|");
        sb.append(contactByWechatReferenceId);
        sb.append("|");
        sb.append(contactByTelegramReferenceId);
        sb.append("|");
        sb.append(agreeForRegistration);
        sb.append("|");
        sb.append(taxgroup);
        sb.append("|");
        sb.append(customerUuid);
        return sb.toString(); 
    } 

}
